import React, { useState } from "react";
import VerifiedCard from "./VerifiedCard";
import { useDispatch, useSelector } from "react-redux";
import commanService from "../../../CommanService/commanService";
import { RandomId } from "../../../CommanFunctions/commanFunctions";
import { verificationStatusAction } from "../../../Redux/action";
import Notification from "../../../CommanUIComp/Notification/Notification";

const Verification = (props) => {
  const dispatch = useDispatch();
  const storeEntityId = useSelector((state) => state.storeEntityId);
  const loginData = useSelector((state) => state.loginData);
  const isLogin = Object.keys(loginData).length > 0;

  const [code, setCode] = useState("");
  const [codeError, setCodeError] = useState("");
  const [authAppName, setAuthAppName] = useState("");
  const [authAppNameError, setAuthAppNameError] = useState("");
  const [isAuthenticate, setIsAuthenticate] = useState(false);

  const [toastShow, setToastOpen] = useState(false);
  const [toastMsg, setToastMsg] = useState("");
  const [isSuccess, setIsSuccess] = useState(false);

  const handleChange = (event) => {
    if (/^\d*$/.test(event.target.value) && event.target.value.length <= 6) {
      setCode(event.target.value);
      setCodeError("");
    }
  };

  const handleVerifyCode = () => {
    const codeVerification = {
      SITDeveloper: "1",
      a: "CodeVerification",
      entity_id: storeEntityId.entity_id,
      store_id: storeEntityId.mini_program_id,
      secret_key: storeEntityId.secret_key,
      tenant_id: storeEntityId.tenant_id,
      code: code,
      member_id: isLogin ? loginData.member_id : RandomId,
      create_by: isLogin ? loginData.member_id : RandomId,
      authnticator_name: authAppName,
    };
    if (authAppName.length > 0 && code.length === 6) {
      commanService
        .postApi("/TwoFactorAuthntication", codeVerification)
        .then((response) => {
          if (response.data.success === 1) {
            if (authAppName.length > 0) {
              setCodeError("");
              setIsAuthenticate(true);
              setAuthAppNameError("");
              dispatch(verificationStatusAction(response.data.success));
            } else {
              setAuthAppNameError("Authenticator App Name Require");
            }
            setToastOpen(true);
            setIsSuccess(true);
            setToastMsg(response.data.message);
          } else {
            setCodeError(response.data.message);
            if (authAppName.length < 1) {
              setAuthAppNameError("Authenticator App Name Require");
            }
            setToastOpen(true);
            setToastMsg(response.data.message);
            setIsSuccess(false);
          }
        });
    } else if (code.length < 6) {
      setCodeError("Please enter atleast 6 digit code");
    } else if (authAppName === "") {
      setAuthAppNameError("Authenticator App Name Require");
    }
  };

  const handlePrevious = () => {
    if (props.setVerificationStep) {
      props.setVerificationStep(1);
    }
  };

  return (
    <React.Fragment>
      {isAuthenticate ? (
        <VerifiedCard setIsAuthenticate={setIsAuthenticate} />
      ) : (
        <div className="bg-white p-20px">
          <header className="py-1">
            <h1 className="fw-500 fs-24px">2-Step Verification</h1>
          </header>

          <main className="my-2">
            <p className="fw-400 fs-16px mb-10px">
              Enter the code generated By Your device.
            </p>
            <div className="mb-10px">
              <p>
                {" "}
                <label htmlFor="code" className="fw-semibold">
                  6-digit code *
                </label>
              </p>
              <input
                type="tel"
                name="code"
                value={code}
                onChange={handleChange}
              />
              {codeError && (
                <p className="text-danger my-0">
                  <small>{codeError}</small>
                </p>
              )}
            </div>
            <p className="fw-400 fs-16px mb-10px">
              Enter a Name for your Authenticator App.
            </p>
            <div>
              <p>
                {" "}
                <label htmlFor="authenticator-name" className="fw-semibold">
                  Authenticator Name *
                </label>{" "}
              </p>
              <input
                type="text"
                value={authAppName}
                onChange={(event) => {
                  setAuthAppName(event.target.value);
                  setAuthAppNameError("");
                }}
              />
              {authAppNameError && (
                <p className="text-danger my-0">
                  <small>{authAppNameError}</small>
                </p>
              )}
            </div>
          </main>

          <footer className="d-flex gap-2 p-2">
            <div>
              {" "}
              <button
                type="button"
                className="btn bg-secondary bg-opacity-25 text-dark px-3"
                onClick={handlePrevious}
              >
                Previous
              </button>
            </div>
            <div>
              {" "}
              <button
                type="button"
                className="btn profilte-btn"
                onClick={handleVerifyCode}
              >
                NEXT
              </button>
            </div>
          </footer>
        </div>
      )}
      <Notification
        toastMsg={toastMsg}
        toastShow={toastShow}
        isSuccess={isSuccess}
        Close={() => setToastOpen(false)}
      />
    </React.Fragment>
  );
};

export default Verification;
